# Install and import torch
%pip install torch
```python
import torch
```


In [ ]:
import torch

print(torch.__version__)



ModuleNotFoundError: No module named 'numpy'

# Basic
## Tensor


In [ ]:
data = [[1, 2], [3, 4]]
# convert array to torch tensor
torch_data = torch.tensor(data)
print("data from list: \n", torch_data)

# one like matrix
one = torch.ones(2, 2)
print("one matrix: \n", one)

# random matrix
rand = torch.rand(2, 2)
print("rand matrix: \n", rand)

shape = (4, 5, )
rand_with_shape = torch.rand(shape)
ones_with_shape = torch.ones(shape)

print("rand with shape: \n", rand_with_shape)
print("ones with shape: \n", ones_with_shape)


data from list: 
 tensor([[1, 2],
        [3, 4]])
one matrix: 
 tensor([[1., 1.],
        [1., 1.]])
rand matrix: 
 tensor([[0.1002, 0.5890],
        [0.3953, 0.4386]])
rand with shape: 
 tensor([[0.7326, 0.4960, 0.7324, 0.5367, 0.8572],
        [0.8464, 0.6745, 0.6243, 0.8441, 0.6333],
        [0.4928, 0.2069, 0.9205, 0.7105, 0.1222],
        [0.2998, 0.4963, 0.9469, 0.6307, 0.0445]])
ones with shape: 
 tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])


## Attr of a torch.tensor

In [ ]:
sample_tensor = torch.tensor((3, 4), dtype=torch.float32)

print("shape of sample tensor: ", sample_tensor.shape)
print("datatype of sample tensor: ", sample_tensor.dtype)
print("tensor on device: ", sample_tensor.device)

# move tensor to apple mps
if torch.accelerator.is_available():
    print("accelerate is available, with device: ", torch.accelerator.current_accelerator())
    sample_tensor = sample_tensor.to("mps")
    print("tensor on device: ", sample_tensor.device)


shape of sample tensor:  torch.Size([2])
datatype of sample tensor:  torch.float32
tensor on device:  cpu
accelerate is available, with device:  mps
tensor on device:  mps:0


# Tensor slicing